### ISSUE TITLE
Teamserver connection continually dies

### ISSUE THREAD

**Issue by KyleEvers** [cisagov/cool-system#81] opened 2020-09-28 13:17 UTC
# 🐛 Bug Report

At least once an hour our Teamserver instance that our CobaltStrike teamserver is running on has its connection die. The instance becomes unreachable until the it is manually rebooted by the COOL team. This is the only instance with this behavior. It is unclear if it is specific to the instance or the deployment of the CobaltStrike Teamserver on the instance. 

## To Reproduce

- Reboot Teamserver0 in env6
- Wait

## Expected behavior

Not to unexpectedly drop connections

## Any helpful log output

N/A

**Comment by jsf9k** [comment] 2020-09-30 03:17
1. I added `kdump` support to the Teamserver instances, thinking that the instances were locking up because of a kernel panic.  I observed several lockups without any `kdumps` being generated, so a kernel panic is not the culprit.
2. I verified that the Teamserver instances _do not_ lock up if the [`serversetup.sh`](https://github.com/noahpowers/ServerSetup/blob/master/serversetup.sh) script is not run.
3. I verified that the Teamserver instances _do_ lock up if the "Debian prep" option (and only the "Debian prep" option) from `serversetup.sh` is run.
4. I verified that the Teamserver instances _do not_ lock up if [these lines](https://github.com/noahpowers/ServerSetup/blob/master/serversetup.sh#L32-L42) are commented out in `serversetup.sh`.

I don't think the instance is actually freezing; instead, I think that the networking on the instance is crapping out.  This is possibly due to the fact that IPv6 is being disabled while `ufw` (and therefore `iptables`) has IPv6 rules active.  I'd like to identify exactly why those `sysctl` settings cause the instance to seize, but I haven't been able to yet.

@KyleEvers, is it feasible to remove those problematic lines from `serversetup.sh`?  There is no IPv6 access in or out of the instance, so I don't think it makes a difference from a security standpoint.

**Comment by jsf9k** [comment] 2020-10-12 14:11
@KyleEvers confirmed that removing the problematic lines is feasible.  He will test that change when he has time to do so.

**Comment by jsf9k** [comment] 2020-10-14 17:16
Another assessment claims to have run the "Debian prep" option without any alteration and encountered no issues.  I will be gathering more information from them.

**Comment by sei-dspooner** [comment] 2020-10-14 19:27
I ran `serversetup.sh`, option 01 on  a clean teamserver (teamserver1.env7) an hour and have not yet noticed any networking issues. 

This test is in addition to teamserver0.env7 which has been running without interruption for at least 2 days.

**Comment by jsf9k** [comment] 2020-12-23 19:07
@justinforbes - has anyone see this issue in recent weeks?

**Comment by justinforbes** [comment] 2020-12-23 19:08
Not that they have reported to me.

**Comment by jsf9k** [comment] 2020-12-23 19:09
I'll close this issue then.  Feel free to re-open it if this is seen again.

**Closed by jsf9k** 2020-12-23 19:09 UTC
Labels: bug
