### ISSUE TITLE
Kerberos SSO not working on Big Sur

### ISSUE THREAD

**Issue by bra1ncramp** [cisagov/cool-system#157] opened 2021-01-22 19:07 UTC
# 🐛 Summary #

I have been testing the COOL VPN on Big Sur. I am able to successfully connect to the VPN, but am not able to SSO into the FreeIPA. I have reviewed the instructions on this, and am still unable to perform a log in. There are some sites that suggest that this is fixed in an upcoming release of Chrome (version 89). I downloaded the Chrome Canary release (version 90) and I still am unable to log in. This is true not only for Chrome, but also Safari and Firefox.

I suspect that it may have something to do with using the MIT Kerberos instead of the native Heimdal version built into macOS, but do not have enough information to determine. I would appreciate if we could connect and attempt to troubleshoot this together.

Ticket Viewer shows no Ticket

## To reproduce ##

1. Upgrade to Big Sur. Connect to COOL VPN. Get a kerberos ticket. Try to connect to IPA0 from any browser.

## Expected behavior ##

What did you expect to happen that didn't?

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.
![2021-01-22 14-05-22](https://user-images.githubusercontent.com/52966515/105534170-166fd680-5cbb-11eb-8d59-e16b4bb48a1c.png)

**Comment by bra1ncramp** [comment] 2021-01-22 20:08
http://kb.mit.edu/confluence/display/istcontrib/Kerberos+Extras+for+Mac+OS+X+-+Installation+Instructions

Looks like Big Sur is incompatible with MIT Kerberos. I even tried to install the Extras for Mac OS X, but the software said it was not compatible with Big Sur when trying to install.

**Comment by felddy** [comment] 2021-01-25 19:05
I was able to reproduce this behavior on my development machine.

```console
bumpkin ~ ❱ system_profiler -detailLevel mini SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 11.1 (20C69)
      Kernel Version: Darwin 20.2.0
      Time since boot: 4 days 21:57

──────────────────────────────────────────────────────────────────────────────────────────────────────────────── 13:53:36
bumpkin ~ ❱ uname -a 
Darwin bumpkin 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
──────────────────────────────────────────────────────────────────────────────────────────────────────────────── 13:53:55
bumpkin ~ ❱ defaults read com.google.Chrome AuthNegotiateDelegateWhitelist
*.cool.cyber.dhs.gov
──────────────────────────────────────────────────────────────────────────────────────────────────────────────── 13:55:00
bumpkin ~ ❱ defaults read com.google.Chrome AuthServerWhitelist
*.cool.cyber.dhs.gov
──────────────────────────────────────────────────────────────────────────────────────────────────────────────── 13:55:02
bumpkin ~ ❱ klist
Ticket cache: KCM:501
Default principal: xxxx@STAGING.COOL.CYBER.DHS.GOV

Valid starting       Expires              Service principal
01/25/2021 13:50:08  01/26/2021 13:49:58  krbtgt/STAGING.COOL.CYBER.DHS.GOV@STAGING.COOL.CYBER.DHS.GOV
──────────────────────────────────────────────────────────────────────────────────────────────────────────────── 13:55:52

```
Chrome: `Version 88.0.4324.96 (Official Build) (x86_64)`

![image](https://user-images.githubusercontent.com/3229435/105752425-45818480-5f15-11eb-8939-308fc8be3e7c.png)

**Comment by felddy** [comment] 2021-01-25 22:20
I'm working on some of the ideas in here: 
https://support.google.com/chrome/a/thread/78150376?hl=en

Specifically, disabling the Chrome sandbox: `open -a 'Google Chrome' --args --no-sandbox` or running with Chrome Canary.   

I haven't found success yet.

**Comment by bra1ncramp** [comment] 2021-01-25 22:26
I tried that without sandbox. Also tried it with Canary. Didn't work for me. Also, no sandbox is great for testing, but wouldn't want to do that on a permanent basis I'm sure.

I'm thinking the issue is related to MIT vs Heimdal. I'm thinking that the browsers are pulling the ticket from wherever Ticket Viewer is pulling them, and it isn't able to grab the ticket. Notice that the Kerberos ticket is not showing up in Ticket Viewer. The ticket DOES show up in Ticket Viewer in Catalina.

**Comment by felddy** [comment] 2021-01-25 23:19
Adding a couple of other links so I don't lose them: 
 - [ Issue 1148102: AuthNegotiateDelegate and AuthServer policies are not working...](https://bugs.chromium.org/p/chromium/issues/detail?id=1148102)
 -  [Allow mach lookup of com.apple.GSSCred](https://chromium-review.googlesource.com/c/chromium/src/+/2560804)

**Comment by dav3r** [comment] 2021-04-09 19:14
Has anyone attempted or made any progress on this issue?

**Comment by felddy** [comment] 2021-04-27 22:49
> Has anyone attempted or made any progress on this issue?

I have made progress.

I am able to successfully connect to COOL assessment environments using Big Sur `11.3 (20E232)`.  

I will put together some detailed documentation shortly.

**Comment by felddy** [comment] 2021-04-28 16:15
The issue is the default Kerberos credential cache.  The OS Kerberos implementation uses an `API` [credential cache type](https://web.mit.edu/kerberos/krb5-1.12/doc/basic/ccache_def.html#ccache-types): 

```console
❱ /usr/bin/klist 
klist: Cache not found: API:ACA5187C-EE0C-4A41-827B-67A2D7DE34F5
```

The MIT Kerberos implementation installed via brew is using a `KCM` cache type:

```console
❱ klist
klist: Credentials cache 'KCM:501' not found
```

Setting the `KRB5CCNAME` environment variable to a name like `KCM:COOL` will point all both Kerberos implementations to the same location allowing credentials to be correctly discovered and used.

## Testing
```console
❱ system_profiler -detailLevel mini SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 11.3 (20E232)
      Kernel Version: Darwin 20.4.0
      Time since boot: 47 minutes
```
```console
❱ krb5-config --all
Version:     Kerberos 5 release 1.19.1
Vendor:      Massachusetts Institute of Technology
Prefix:      /usr/local/Cellar/krb5/1.19.1
Exec_prefix: /usr/local/Cellar/krb5/1.19.1
```
```console
❱ export KRB5CCNAME=KCM:COOL
```
```console
❱ klist
klist: Credentials cache 'KCM:COOL' not found
```
```console
❱ curl --negotiate --user : --head https://guac.env1.staging.cool.cyber.dhs.gov/#/
curl: (67) Login denied
```
```console
❱ kinit -f mark.feldhousen@STAGING.COOL.CYBER.DHS.GOV
MARK L FELDHOUSEN JR             PIN: 
```
```console
❱ klist
Ticket cache: KCM:COOL
Default principal: mark.feldhousen@STAGING.COOL.CYBER.DHS.GOV

Valid starting       Expires              Service principal
04/28/2021 11:51:03  04/29/2021 10:55:35  krbtgt/STAGING.COOL.CYBER.DHS.GOV@STAGING.COOL.CYBER.DHS.GOV
```
```console
❱ curl --negotiate --user : --head https://guac.env1.staging.cool.cyber.dhs.gov/#/
HTTP/1.1 200 
Date: Wed, 28 Apr 2021 15:51:12 GMT
Server: Apache/2.4.38 (Debian)
WWW-Authenticate: Negotiate ...
Set-Cookie: gssapi_session=MagBearerToken=...;path=/;httponly;secure;
Accept-Ranges: bytes
ETag: W/"5414-1609201462000"
Last-Modified: Tue, 29 Dec 2020 00:24:22 GMT
Content-Type: text/html
Content-Length: 5414
Cache-Control: no-cache
```
# :tada: #
```console
❱ klist
Ticket cache: KCM:COOL
Default principal: mark.feldhousen@STAGING.COOL.CYBER.DHS.GOV

Valid starting       Expires              Service principal
04/28/2021 11:51:03  04/29/2021 10:55:35  krbtgt/STAGING.COOL.CYBER.DHS.GOV@STAGING.COOL.CYBER.DHS.GOV
04/28/2021 11:51:12  04/29/2021 10:55:35  HTTP/guac.env1.staging.cool.cyber.dhs.gov@STAGING.COOL.CYBER.DHS.GOV
```

I have verified this also works with Chrome when its policies are configured as we have documented.  

`KRB5CCNAME` can set for newly launched processed with: `launchctl setenv KRB5CCNAME KCM:COOL` 

To set this at user login the following file can be added:

`~/Library/LaunchAgents/gov.dhs.cyber.cool.EnvironmentVars.plist`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>gov.dhs.cyber.cool.EnvironmentVars</string>
	<key>ProgramArguments</key>
	<array>
		<string>/bin/launchctl</string>
		<string>setenv</string>
		<string>KRB5CCNAME</string>
		<string>KCM:COOL</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>
```

**Comment by felddy** [comment] 2021-04-28 16:47
@justinforbes I believe you too are living that Big Sur life.  This should get you back into the COOL.

**Comment by justinforbes** [comment] 2021-04-29 13:41
The curl command is not working for me, I get could not resolve host.

**Comment by jsf9k** [comment] 2021-04-29 13:52
> The curl command is not working for me, I get could not resolve host.

The curl command @felddy gave will only work on the COOL _staging_ VPN.  If you are instead connected to the COOL _production_ VPN then you should run this command instead:
```
$ curl --negotiate --user : --head https://guac.env1.cool.cyber.dhs.gov/#/
```

**Comment by justinforbes** [comment] 2021-04-29 14:00
That worked for me.

**Comment by bra1ncramp** [comment] 2021-05-04 17:47
```
curl --negotiate --user : --head https://guac.env1.cool.cyber.dhs.gov/#/
curl: (67) Login denied
```

**Comment by dav3r** [comment] 2021-05-04 17:53
@bra1ncramp - You were not assigned to `env1` or any other COOL environments, so I added you to `env3`.  Give this a try now:
```
$ curl --negotiate --user : --head https://guac.env3.cool.cyber.dhs.gov/#/
```
(assuming you have already run `kinit`)

**Comment by bra1ncramp** [comment] 2021-05-04 17:56
do i curl first or kinit first? the example above has curl first
also - should i need to run the curl each time, or is this a one and done? we need to be able to automate this

**Comment by dav3r** [comment] 2021-05-04 17:59
@felddy's example above shows the first `curl` failing (`Login denied`) because he hadn't yet run `kinit`.  Once he does, the next `curl` is successful.

**Comment by bra1ncramp** [comment] 2021-05-04 18:18
ok, I'm following. I was able to get it to work. I had to add the export to the script itself. Even adding it to the user's launch agent only sets it for that user's session. The automated script is run in a different shell environment, so wasn't working correctly. I have made the necessary changes and am able to get it working properly now.

**Closed** 2021-05-07 17:19 UTC
Labels: bug
