### ISSUE TITLE
Additional Tools for Kali System

### ISSUE THREAD

**Issue by justinforbes** [cisagov/cool-system#111] opened 2020-11-03 15:00 UTC
# 🚀 Feature Proposal

Install Flameshot and LibreOffice on the base Kali image.

## Motivation

This will allow team members to take and edit screenshots as well as open Microsoft Office documents on the Kali systems.

**Comment by jsf9k** [comment] 2020-11-03 15:14
Duplicate of cisagov/ansible-role-kali#29 and #100.

**Closed by jsf9k** 2020-11-03 15:14 UTC
Labels: duplicate
