### ISSUE TITLE
Increase RAM on Kali Scanners

### ISSUE THREAD

**Issue by justinforbes** [cisagov/cool-system#110] opened 2020-11-03 14:58 UTC
# 🚀 Feature Proposal

Increase the RAM allocation on each Kali Scanner to 8GB.

## Motivation

This will allow teams to use Burp and other resource intense tools without running into issues.

**Comment by jsf9k** [comment] 2020-11-03 15:12
Duplicate of #106.

**Closed by jsf9k** 2020-11-03 15:12 UTC
Labels: duplicate
