### ISSUE TITLE
Add Python Virtualenv to Kali Image

### ISSUE THREAD

**Issue by justinforbes** [cisagov/cool-system#120] opened 2020-11-09 19:56 UTC
# 🚀 Feature Proposal

Please install the Python2 and Python3 virtualenv packages on the Kali base image.

## Motivation

This will allow python tools to be used within virtual environments preventing dependency issues which can occur when multiple tools require the same packages but at different releases.

## Example

This will be used for any python tool used during testing.

## Pitch

This will prevent issues as packages are updated and requirements change.

**Comment by jsf9k** [comment] 2020-11-09 20:55
I _could_ install the `python3-virtualenv` package on Kali, which would provide the `virtualenv` Python package for the system Python3.  Note, however, that [`pyenv`](https://github.com/pyenv/pyenv) is the dev team's recommended solution for handling multiple Python environments.  I can't stress strongly enough that _using the system Python for your own purposes is a path to misery_.

For what it's worth, `pyenv` [has also been recommended by Kali Linux as a recommended solution for managing the Python2 EOL](https://www.kali.org/docs/general-use/using-eol-python-versions/).  I'm sure you know that, for almost a year, [Kali Linux has been deprecating Python2 support and removing packages that do not upgrade themselves to use Python3](https://www.kali.org/news/python-2-end-of-life/).  They essentially have no choice, since Kali Linux is based on Debian Testing (currently Debian Bullseye) and Python2 is quickly being phased out of there.

The previous paragraph explains why there is no package analogous to `python3-virtualenv` for the system Python2 on Kali.  I _could_ install `virtualenv` under the system Python2 via `pip`, but if you guys are going to continue using Python2 then it makes a lot of sense for you to move to `pyenv` instead of relying on Kali.

@dav3r or @felddy, feel free to chime in if you have thoughts.

**Comment by felddy** [comment] 2020-11-09 21:08
I agree with @jsf9k.  Sticking with `pyenv` and decoupling from the system Python will future-proof a lot of the tooling on Kali.  This also jibes with the [instructions and scripts](https://github.com/cisagov/skeleton-docker/blob/develop/CONTRIBUTING.md#setting-up-pre-commit) that are staples of all of the skeleton-based projects.

**Comment by jsf9k** [comment] 2020-11-09 21:52
@justinforbes, we think what makes sense would be if we pre-create `pyenv` environments for each of the Python tools we install for you from GitHub.  Then, if you `cd /tools/SharpShooter`, for example, you will automatically be in a `pyenv` environment with its own python interpreter and all the dependencies needed to run SharpShooter.

**Would this meet your needs?**  It would allow us to avoid installing stuff to the system Python, and the tools should work for you guys with minimal setup.  It seems like a win-win.

One caveat is that I seem to recall that some of the Python tools you guys requested do not specify their dependencies with a `setup.py` or requirements file.  We could set up a `pyenv` environment for those tools, but we obviously can't install the dependencies for you.

**Comment by justinforbes** [comment] 2020-11-09 21:53
That would be perfect, thanks.

**Comment by jsf9k** [comment] 2020-11-10 15:55
Duplicate of [cisagov/ansible-role-kali#12](https://github.com/cisagov/ansible-role-kali/issues/12).

**Closed by jsf9k** 2020-11-10 15:55 UTC
Labels: enhancement
